### ISSUE TITLE
404 on the Art Gallery images in README.md

### ISSUE THREAD

**Issue by BenzaitenS** [artflow-vr/artflow#37]
The images in the "Art Gallery" section of the README refer to resources previously hosted on your GitHub page 😢

**Comment by DavidPeicho** [comment]
I don't have them anymore. If @AurelienLeandri has them I can directly add them to the markdown.

**Comment by BenzaitenS** [comment]
We still have them in our final presentation slides, maybe you can get them from this 🤷

**Comment by DavidPeicho** [comment]
![1](https://user-images.githubusercontent.com/8783766/93022731-a2257800-f5e2-11ea-91f9-f70798480f7c.png)
![2](https://user-images.githubusercontent.com/8783766/93022733-a5206880-f5e2-11ea-85ca-1dc8bb8c3d0b.png)
![3](https://user-images.githubusercontent.com/8783766/93022735-a6519580-f5e2-11ea-927d-bd1e2a9dcfd7.png)

Okay thanks. Will update the README with those
